### ISSUE TITLE
searchUri should use npm's configured registry

### ISSUE THREAD

**Issue by mralexgray** [wires/npm-keywordsearch#1]
Love the module.. wish it checked my `nam config` for things like `registry`, though...

**Comment by wires** [comment]
Thanks, great to hear! I think you mean `npm config`? In any case, I pass the registry url to [`npm-registry-client`](https://github.com/npm/npm-registry-client) so this is something I can set up. I'm not exactly sure where to get that url from? `~/.npmrc`? Could you point me to some docs?

**Comment by wires** [comment]
example to change registry `npm config set registry="http://ipm.iotjs.net:5984/registry/_design/app/_rewrite"`

**Comment by wires** [comment]
The four relevant files are:
- per-project config file (/path/to/my/project/.npmrc)
-  per-user config file (~/.npmrc)
-   global config file ($PREFIX/etc/npmrc)
-    npm builtin config file (/path/to/npm/npmrc)

**Comment by wires** [comment]
There doesn't seem to be a good, canonical way to determine the npm-registry settings. So I've update the module so that you can optionally pass a registry URL yourself, will push and release soon.
